services:
  application:
    image: domainservice
    container_name: domain-service
    env_file:
      - .env
    depends_on:
      - nats
      - mongo
    ports:
      - "8081:8081"
    profiles:
      - dev

  gateway:
    image: gateway
    container_name: gateway
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - nats
    profiles:
      - dev

  nats:
    image: nats:2.10.22
    container_name: nats-server
    ports:
      - "4222:4222"
    profiles:
      - test
      - dev

  mongo:
    image: mongo:7.0.12
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    profiles:
      - dev

  mongo-express:
    image: mongo-express:1.0.2
    container_name: express
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/
    profiles:
      - dev

  kafka:
    image: confluentinc/confluent-local:7.4.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
    profiles:
      - test
      - dev

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "8888:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    profiles:
      - dev

volumes:
  mongo_data:
  mongo_config:
