services:
  application:
    build:
      context: .
    container_name: application
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      database: ${database}
      username: ${mongo_username}
      password: ${mongo_password}
      authentication_database: ${authentication_database}
      mongo_host: ${mongo_host}
      mongo_port: ${mongo_port}

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongo_username}
      MONGO_INITDB_ROOT_PASSWORD: ${mongo_password}
      MONGO_INITDB_DATABASE: ${database}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    container_name: express
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${mongo_username}:${mongo_password}@${mongo_host}:${mongo_port}/

volumes:
  mongo_data:
  mongo_config:
