services:
  application:
    image: domainservice
    container_name: domain-service
    env_file:
      - .env
    depends_on:
      - nats
      - mongo
    ports:
      - "8081:8081"
    profiles:
      - dev

  gateway:
    image: gateway
    container_name: gateway
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - nats
    profiles:
      - dev

  nats:
    image: nats:2.10.22
    container_name: nats-server
    ports:
      - "4222:4222"
    profiles:
      - test
      - dev

  mongo:
    image: mongo:7.0.12
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    profiles:
      - dev

  mongo-express:
    image: mongo-express:1.0.2
    container_name: express
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8085:8085"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/
    profiles:
      - dev

volumes:
  mongo_data:
  mongo_config:
