spring:
  application:
    name: rentcar

  data:
    mongodb:
      host: localhost
      port: 27017
      database: cars
      username: mongoadmin
      password: mongopassword
      authentication-database: admin

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
