spring:
  application:
    name: rentcar

  data:
    mongodb:
      uri: mongodb://${username}:${password}@${mongo_host}:${mongo_port}/${database}?authSource=${authentication_database}

server:
  servlet:
    contextPath: /api/v1
