spring:
  application:
    name: rentcar

  data:
    mongodb:
      uri: mongodb://${USERNAME}:${PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${DATABASE}?authSource=admin

server:
  servlet:
    contextPath: /api/v1

management:
  endpoint:
    health:
      probes:
        enabled: true
