spring:
  application:
    name: rentcar

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${DATABASE}?authSource=admin
      auto-index-creation: true

mongock:
  migration-scan-package: com.makarytskyi.rentcar.mongock.migration

server:
  servlet:
    contextPath: /api/v1

management:
  endpoint:
    health:
      probes:
        enabled: true
