spring:
  application:
    name: gateway

server:
  servlet:
    contextPath: /api/v1

nats:
  spring:
    io.nats.client:
      servers: "nats://localhost:4222"

grpc:
  server:
    port: 50051
    security:
      enabled: false
