apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-depl
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: application
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8081
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 4
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: database
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo_host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo_port
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-configmap
                  key: nats_url

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
