spring:
  application:
    name: rentcar

  kafka:
    consumer:
      auto-offset-reset: latest
      properties:
        session.timeout.ms: 10000
        max.poll.interval.ms: 10000
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${DATABASE}?authSource=admin

mongock:
  migration-scan-package: com.makarytskyi.rentcar.mongock.migration

server:
  port: 8081
  servlet:
    contextPath: /api/v1

management:
  endpoint:
    health:
      probes:
        enabled: true

nats:
  url: ${NATS_URL}
