name: Build CarRent

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Run gradle build
        run: ./gradlew build

      - name: Delta Coverage check
        if: ${{ github.event_name == 'pull_request' && success() }}
        run: ./gradlew deltaCoverage -PdiffBase="refs/remotes/origin/$GITHUB_BASE_REF"